server:
  port: 8090
  ssl:
    key-store: star/key/certificate.p12
    key-store-password: 12345678
    key-store-type: PKCS12
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/paper
    driver-class-name: com.mysql.cj.jdbc.Driver
    username:  root
    password: 12345678
